### ISSUE TITLE
Make 'delete' command flexible

### ISSUE THREAD

**Issue by samsontmr** [CS2103AUG2016-T14-C3/main#25]
Currently requires list to delete by list index.
Add support for use case where user types delete [non-number keyword]—GUI will display a list of items matching keyword. User can then choose items to delete using index
Add support for deleting multiple entries at once

**Comment by kaiyanyeo** [comment]
Currently requires list to delete by list index.
To do:
- Add support for deleting multiple entries at once.
- Add support for deleting all entries listed from a find command
