### ISSUE TITLE
As a user I want to add tasks

### ISSUE THREAD

**Issue by samsontmr** [CS2103AUG2016-T14-C3/main#3]
So that I can keep track of my tasks

**Comment by patrickcho168** [comment]
adding task, event, deadline done
add task n/gogo
add deadline n/baba ed/2016-08-08 et/18:00
add event n/rara sd/2016-08-08 et/18:00 ed/2016-09-09 et/19:00

Todo:
- Logic for ensuring that end date and end time are after start date and start time.
- Current regex allows for dates such as 2016-02-31.
