### ISSUE TITLE
Implement logic support for finding floating tasks

### ISSUE THREAD

**Issue by samsontmr** [CS2103AUG2016-T14-C3/main#6]

**Comment by patrickcho168** [comment]
Done for Task, Deadline and Event.
Need to do more verification of date and time though. Currently, anything of the form YYYY-MM-DD passes for date and anything of the form HH:SS passes for time. This leads to inaccuracies such as dates like 9999-99-99 and accurate times such as 1:00 not being accepted.

**Comment by patrickcho168** [comment]
search not implemented yet.
