### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by hang15** [CS2103AUG2016-T14-C3/main#91]
## Developer Guide
- Architecture
  - Are you using the same architecture as AddressBook? Do reflect any changes (if any) in your diagram.
- Product Survey
  - Please format your product survey. It is not very readable.
  - Product survey can be more extensive.
## User Guide
- Do continue to update your user guide
- You can separate your input format and input examples. Give a general input format, followed by one or two examples of actual usage.
- Please complete FAQ section
- You may want to include an example in the command summary section as well

**Comment by samsontmr** [comment]
Thanks for the comments! The product survey was supposed to be in a table like the user stories; we must have missed out some important markdown characters
